#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import json
import time
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


MODELS = ("complex", "transr", "transe", "distmult")
FORBIDDEN_MODEL_COLUMNS = {
    "hidden_group_id",
    "source_group_id",
    "target_group_id",
    "group_id",
    "hidden_seniority_rank",
    "seniority",
    "rank",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run knowledge-graph embedding baselines on a binary relation table. "
            "The input CSV must contain entity_1, entity_2, label, and split."
        )
    )
    parser.add_argument(
        "--data-path",
        type=Path,
        default=Path("minimal_symmetry_dataset") / "symmetry_friendship_atoms.csv",
        help="Model-facing CSV generated by one of the minimal relation dataset generators.",
    )
    parser.add_argument("--output-dir", type=Path, default=Path("kge_relation_results"))
    parser.add_argument("--models", type=str, default="complex,transr,transe,distmult")
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--seed", type=int, default=20260429)
    parser.add_argument("--embedding-dim", type=int, default=64)
    parser.add_argument(
        "--relation-dim",
        type=int,
        default=64,
        help="Relation-space dimension used by TransR.",
    )
    parser.add_argument("--epochs", type=int, default=1000)
    parser.add_argument("--lr", type=float, default=0.01)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--patience", type=int, default=100)
    parser.add_argument("--max-grad-norm", type=float, default=5.0)
    parser.add_argument("--distance", type=str, default="l2", choices=["l1", "l2"])
    parser.add_argument("--decision-threshold", type=float, default=0.5)
    parser.add_argument(
        "--threshold-mode",
        type=str,
        default="fixed",
        choices=["fixed", "tune_validation_f1"],
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate the dataset and print the run plan without importing torch or sklearn.",
    )
    return parser.parse_args()


def parse_csv_list(text: str) -> list[str]:
    return [part.strip().lower() for part in text.split(",") if part.strip()]


def validate_args(args: argparse.Namespace) -> list[str]:
    selected_models = parse_csv_list(args.models)
    unknown_models = sorted(set(selected_models) - set(MODELS))
    if unknown_models:
        raise ValueError(f"Unknown model(s): {unknown_models}. Valid options are {list(MODELS)}.")
    if not selected_models:
        raise ValueError("No models selected.")
    if not args.data_path.exists():
        raise FileNotFoundError(f"Dataset not found: {args.data_path}")
    if args.embedding_dim <= 0:
        raise ValueError("--embedding-dim must be positive.")
    if args.relation_dim <= 0:
        raise ValueError("--relation-dim must be positive.")
    if args.epochs <= 0:
        raise ValueError("--epochs must be positive.")
    if args.lr <= 0.0:
        raise ValueError("--lr must be positive.")
    if args.weight_decay < 0.0:
        raise ValueError("--weight-decay must be non-negative.")
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be positive.")
    if args.patience < 0:
        raise ValueError("--patience must be non-negative.")
    if args.max_grad_norm < 0.0:
        raise ValueError("--max-grad-norm must be non-negative.")
    if not 0.0 <= args.decision_threshold <= 1.0:
        raise ValueError("--decision-threshold must be in [0, 1].")
    return selected_models


def import_runtime_dependencies() -> None:
    global np
    global torch
    global accuracy_score
    global average_precision_score
    global f1_score
    global precision_score
    global recall_score
    global roc_auc_score

    try:
        import numpy as np_module
        import torch as torch_module
        from sklearn.metrics import accuracy_score as accuracy_score_fn
        from sklearn.metrics import average_precision_score as average_precision_score_fn
        from sklearn.metrics import f1_score as f1_score_fn
        from sklearn.metrics import precision_score as precision_score_fn
        from sklearn.metrics import recall_score as recall_score_fn
        from sklearn.metrics import roc_auc_score as roc_auc_score_fn
    except ModuleNotFoundError as exc:
        raise SystemExit(
            f"Missing Python dependency: {exc.name}. Run this script in an environment with "
            "numpy, torch, and scikit-learn installed."
        ) from exc

    np = np_module
    torch = torch_module
    accuracy_score = accuracy_score_fn
    average_precision_score = average_precision_score_fn
    f1_score = f1_score_fn
    precision_score = precision_score_fn
    recall_score = recall_score_fn
    roc_auc_score = roc_auc_score_fn


def load_dataset_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)

    if not rows:
        raise ValueError("Dataset is empty.")

    actual_columns = set(rows[0])
    required = {"entity_1", "entity_2", "label", "split"}
    missing = sorted(required - actual_columns)
    if missing:
        raise ValueError(f"Dataset is missing required columns: {missing}")

    forbidden = sorted(FORBIDDEN_MODEL_COLUMNS & actual_columns)
    if forbidden:
        raise ValueError(f"Model-facing dataset contains hidden/leakage columns: {forbidden}")

    splits = {str(row["split"]) for row in rows}
    unknown_splits = splits - {"train", "validation", "test"}
    if unknown_splits:
        raise ValueError(f"split must contain only train, validation, and test. Got {sorted(unknown_splits)}.")

    try:
        labels = [int(row["label"]) for row in rows]
    except ValueError as exc:
        raise ValueError("label must be binary 0/1.") from exc
    if set(labels) - {0, 1}:
        raise ValueError("label must be binary 0/1.")

    train_labels = [int(row["label"]) for row in rows if row["split"] == "train"]
    test_labels = [int(row["label"]) for row in rows if row["split"] == "test"]
    if not train_labels or not test_labels:
        raise ValueError("Dataset must contain non-empty train and test splits.")
    if len(set(train_labels)) < 2:
        raise ValueError("Train split must contain both classes.")
    if len(set(test_labels)) < 2:
        raise ValueError("Test split must contain both classes.")
    return rows


def build_entity_mapping(rows: list[dict[str, str]]) -> tuple[list[str], dict[str, int]]:
    entities = sorted({row["entity_1"] for row in rows} | {row["entity_2"] for row in rows})
    return entities, {entity_id: idx for idx, entity_id in enumerate(entities)}


def encode_rows(rows: list[dict[str, str]], entity_to_idx: dict[str, int]) -> tuple[Any, Any]:
    pairs = np.asarray(
        [[entity_to_idx[row["entity_1"]], entity_to_idx[row["entity_2"]]] for row in rows],
        dtype=np.int64,
    )
    labels = np.asarray([int(row["label"]) for row in rows], dtype=np.int64)
    return pairs, labels


def best_f1_threshold(y_true: Any, positive_proba: Any, default_threshold: float) -> float:
    if len(y_true) == 0 or np.unique(y_true).size < 2:
        return float(default_threshold)
    candidates = np.unique(np.concatenate([np.linspace(0.0, 1.0, 101), positive_proba, [default_threshold]]))
    best_threshold = float(default_threshold)
    best_score = -1.0
    for threshold in candidates:
        score = float(f1_score(y_true, (positive_proba >= threshold).astype(np.int64), zero_division=0))
        if score > best_score:
            best_score = score
            best_threshold = float(threshold)
    return best_threshold


def evaluate_predictions(y_true: Any, y_pred: Any, positive_proba: Any) -> dict[str, float]:
    metrics = {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "positive_rate_true": float(np.mean(y_true)),
        "positive_rate_pred": float(np.mean(y_pred)),
    }
    if np.unique(y_true).size < 2:
        metrics["average_precision"] = float("nan")
        metrics["roc_auc"] = float("nan")
    else:
        metrics["average_precision"] = float(average_precision_score(y_true, positive_proba))
        metrics["roc_auc"] = float(roc_auc_score(y_true, positive_proba))
    return metrics


def build_model(model_name: str, *, num_entities: int, args: argparse.Namespace) -> Any:
    class DistMultModel(torch.nn.Module):
        def __init__(self, entity_count: int, embedding_dim: int) -> None:
            super().__init__()
            self.entity_embeddings = torch.nn.Embedding(entity_count, embedding_dim)
            self.relation = torch.nn.Parameter(torch.empty(embedding_dim))
            self.bias = torch.nn.Parameter(torch.zeros(()))
            torch.nn.init.xavier_uniform_(self.entity_embeddings.weight)
            torch.nn.init.normal_(self.relation, mean=0.0, std=1.0 / embedding_dim**0.5)

        def forward(self, pairs: Any) -> Any:
            left = self.entity_embeddings(pairs[:, 0])
            right = self.entity_embeddings(pairs[:, 1])
            return (left * self.relation * right).sum(dim=1) + self.bias

    class ComplExModel(torch.nn.Module):
        def __init__(self, entity_count: int, embedding_dim: int) -> None:
            super().__init__()
            self.entity_real = torch.nn.Embedding(entity_count, embedding_dim)
            self.entity_imag = torch.nn.Embedding(entity_count, embedding_dim)
            self.relation_real = torch.nn.Parameter(torch.empty(embedding_dim))
            self.relation_imag = torch.nn.Parameter(torch.empty(embedding_dim))
            self.bias = torch.nn.Parameter(torch.zeros(()))
            torch.nn.init.xavier_uniform_(self.entity_real.weight)
            torch.nn.init.xavier_uniform_(self.entity_imag.weight)
            torch.nn.init.normal_(self.relation_real, mean=0.0, std=1.0 / embedding_dim**0.5)
            torch.nn.init.normal_(self.relation_imag, mean=0.0, std=1.0 / embedding_dim**0.5)

        def forward(self, pairs: Any) -> Any:
            left_real = self.entity_real(pairs[:, 0])
            left_imag = self.entity_imag(pairs[:, 0])
            right_real = self.entity_real(pairs[:, 1])
            right_imag = self.entity_imag(pairs[:, 1])
            score = (
                left_real * self.relation_real * right_real
                + left_imag * self.relation_real * right_imag
                + left_real * self.relation_imag * right_imag
                - left_imag * self.relation_imag * right_real
            ).sum(dim=1)
            return score + self.bias

    class TransEModel(torch.nn.Module):
        def __init__(self, entity_count: int, embedding_dim: int, distance: str) -> None:
            super().__init__()
            self.entity_embeddings = torch.nn.Embedding(entity_count, embedding_dim)
            self.relation = torch.nn.Parameter(torch.empty(embedding_dim))
            self.margin = torch.nn.Parameter(torch.tensor(1.0))
            self.log_scale = torch.nn.Parameter(torch.tensor(0.0))
            self.bias = torch.nn.Parameter(torch.zeros(()))
            self.norm_p = 1 if distance == "l1" else 2
            torch.nn.init.xavier_uniform_(self.entity_embeddings.weight)
            torch.nn.init.normal_(self.relation, mean=0.0, std=1.0 / embedding_dim**0.5)

        def forward(self, pairs: Any) -> Any:
            left = self.entity_embeddings(pairs[:, 0])
            right = self.entity_embeddings(pairs[:, 1])
            distance = torch.linalg.vector_norm(left + self.relation - right, ord=self.norm_p, dim=1)
            scale = torch.nn.functional.softplus(self.log_scale) + 1e-6
            return scale * (self.margin - distance) + self.bias

    class TransRModel(torch.nn.Module):
        def __init__(self, entity_count: int, embedding_dim: int, relation_dim: int, distance: str) -> None:
            super().__init__()
            self.entity_embeddings = torch.nn.Embedding(entity_count, embedding_dim)
            self.projection = torch.nn.Parameter(torch.empty(relation_dim, embedding_dim))
            self.relation = torch.nn.Parameter(torch.empty(relation_dim))
            self.margin = torch.nn.Parameter(torch.tensor(1.0))
            self.log_scale = torch.nn.Parameter(torch.tensor(0.0))
            self.bias = torch.nn.Parameter(torch.zeros(()))
            self.norm_p = 1 if distance == "l1" else 2
            torch.nn.init.xavier_uniform_(self.entity_embeddings.weight)
            self._init_projection(relation_dim, embedding_dim)
            torch.nn.init.normal_(self.relation, mean=0.0, std=1.0 / relation_dim**0.5)

        def _init_projection(self, relation_dim: int, embedding_dim: int) -> None:
            with torch.no_grad():
                self.projection.zero_()
                diagonal = min(relation_dim, embedding_dim)
                self.projection[:diagonal, :diagonal] = torch.eye(diagonal)
                self.projection.add_(0.01 * torch.randn_like(self.projection))

        def forward(self, pairs: Any) -> Any:
            left = self.entity_embeddings(pairs[:, 0])
            right = self.entity_embeddings(pairs[:, 1])
            projected_left = torch.nn.functional.linear(left, self.projection)
            projected_right = torch.nn.functional.linear(right, self.projection)
            distance = torch.linalg.vector_norm(
                projected_left + self.relation - projected_right,
                ord=self.norm_p,
                dim=1,
            )
            scale = torch.nn.functional.softplus(self.log_scale) + 1e-6
            return scale * (self.margin - distance) + self.bias

    if model_name == "complex":
        return ComplExModel(num_entities, args.embedding_dim)
    if model_name == "transr":
        return TransRModel(num_entities, args.embedding_dim, args.relation_dim, args.distance)
    if model_name == "transe":
        return TransEModel(num_entities, args.embedding_dim, args.distance)
    if model_name == "distmult":
        return DistMultModel(num_entities, args.embedding_dim)
    raise ValueError(f"Unsupported model: {model_name}")


def tensorize(pairs: Any, labels: Any, *, device: Any) -> tuple[Any, Any]:
    pair_tensor = torch.as_tensor(pairs, dtype=torch.long, device=device)
    label_tensor = torch.as_tensor(labels.astype(np.float32), dtype=torch.float32, device=device)
    return pair_tensor, label_tensor


def fit_predict_one_model(
    *,
    model_name: str,
    num_entities: int,
    train_pairs_np: Any,
    y_train: Any,
    valid_pairs_np: Any,
    y_valid: Any,
    test_pairs_np: Any,
    args: argparse.Namespace,
) -> dict[str, object]:
    if args.device.startswith("cuda") and not torch.cuda.is_available():
        raise RuntimeError(f"Requested device {args.device!r}, but CUDA is not available to PyTorch.")
    device = torch.device(args.device)

    torch.manual_seed(args.seed)
    if device.type == "cuda":
        torch.cuda.manual_seed_all(args.seed)

    model = build_model(model_name, num_entities=num_entities, args=args).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    loss_fn = torch.nn.BCEWithLogitsLoss()

    train_pairs, train_labels = tensorize(train_pairs_np, y_train, device=device)
    valid_pairs, valid_labels = tensorize(valid_pairs_np, y_valid, device=device)
    test_pairs = torch.as_tensor(test_pairs_np, dtype=torch.long, device=device)
    batch_size = min(args.batch_size, len(train_pairs))

    fit_start = time.perf_counter()
    best_loss = float("inf")
    best_epoch = 0
    best_state: dict[str, Any] | None = None
    epochs_without_improvement = 0
    epochs_run = 0

    for epoch in range(1, args.epochs + 1):
        epochs_run = epoch
        model.train()
        permutation = torch.randperm(len(train_pairs), device=device)
        for start in range(0, len(train_pairs), batch_size):
            batch_idx = permutation[start : start + batch_size]
            optimizer.zero_grad(set_to_none=True)
            logits = model(train_pairs[batch_idx])
            loss = loss_fn(logits, train_labels[batch_idx])
            loss.backward()
            if args.max_grad_norm > 0.0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.max_grad_norm)
            optimizer.step()

        model.eval()
        with torch.no_grad():
            if len(valid_pairs):
                monitor_loss = float(loss_fn(model(valid_pairs), valid_labels).detach().cpu())
            else:
                monitor_loss = float(loss_fn(model(train_pairs), train_labels).detach().cpu())

        if monitor_loss < best_loss - 1e-7:
            best_loss = monitor_loss
            best_epoch = epoch
            best_state = {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1
            if args.patience and epochs_without_improvement >= args.patience:
                break

    if best_state is not None:
        model.load_state_dict({key: value.to(device) for key, value in best_state.items()})
    fit_time_s = time.perf_counter() - fit_start

    pred_start = time.perf_counter()
    model.eval()
    with torch.no_grad():
        valid_logits = model(valid_pairs) if len(valid_pairs) else torch.empty(0, device=device)
        test_logits = model(test_pairs)
        valid_proba = torch.sigmoid(valid_logits).detach().cpu().numpy().astype(np.float64)
        test_proba = torch.sigmoid(test_logits).detach().cpu().numpy().astype(np.float64)
    predict_time_s = time.perf_counter() - pred_start

    threshold = (
        best_f1_threshold(y_valid, valid_proba, args.decision_threshold)
        if args.threshold_mode == "tune_validation_f1"
        else float(args.decision_threshold)
    )
    y_pred = (test_proba >= threshold).astype(np.int64)
    return {
        "positive_proba": test_proba,
        "y_pred": y_pred,
        "threshold": float(threshold),
        "fit_time_s": float(fit_time_s),
        "predict_time_s": float(predict_time_s),
        "epochs_run": int(epochs_run),
        "best_epoch": int(best_epoch),
        "best_monitor_loss": float(best_loss),
    }


def write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def build_findings(metric_rows: list[dict[str, object]], args: argparse.Namespace) -> str:
    lines = [
        "# KGE Relation Baseline Findings",
        "",
        f"- data path: `{args.data_path}`",
        f"- threshold mode: `{args.threshold_mode}`",
        f"- device: `{args.device}`",
        f"- embedding dim: `{args.embedding_dim}`",
        f"- relation dim: `{args.relation_dim}`",
        "",
        "| Model | Accuracy | F1 | Average Precision | ROC AUC | Threshold | Best Epoch |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in sorted(metric_rows, key=lambda item: str(item["model"])):
        lines.append(
            "| {model} | {accuracy:.4f} | {f1:.4f} | {average_precision:.4f} | {roc_auc:.4f} | "
            "{threshold:.4f} | {best_epoch} |".format(**row)
        )
    return "\n".join(lines) + "\n"


def print_dry_run(
    *,
    args: argparse.Namespace,
    selected_models: list[str],
    entity_count: int,
    train_rows: list[dict[str, str]],
    valid_rows: list[dict[str, str]],
    test_rows: list[dict[str, str]],
) -> None:
    print(f"data_path: {args.data_path.resolve()}")
    print(f"models: {selected_models}")
    print(f"entities: {entity_count}")
    print(f"train_rows: {len(train_rows)}")
    print(f"validation_rows: {len(valid_rows)}")
    print(f"test_rows: {len(test_rows)}")
    print(f"embedding_dim: {args.embedding_dim}")
    print(f"relation_dim: {args.relation_dim}")
    print(f"epochs: {args.epochs}")
    print("train_label_counts:")
    for label, count in sorted(Counter(int(row["label"]) for row in train_rows).items()):
        print(f"{label}    {count}")
    print("test_label_counts:")
    for label, count in sorted(Counter(int(row["label"]) for row in test_rows).items()):
        print(f"{label}    {count}")


def main() -> None:
    args = parse_args()
    selected_models = validate_args(args)
    rows = load_dataset_rows(args.data_path)
    entity_categories, entity_to_idx = build_entity_mapping(rows)

    train_rows = [row for row in rows if row["split"] == "train"]
    valid_rows = [row for row in rows if row["split"] == "validation"]
    test_rows = [row for row in rows if row["split"] == "test"]

    if args.dry_run:
        print_dry_run(
            args=args,
            selected_models=selected_models,
            entity_count=len(entity_categories),
            train_rows=train_rows,
            valid_rows=valid_rows,
            test_rows=test_rows,
        )
        return

    import_runtime_dependencies()

    train_pairs_np, y_train = encode_rows(train_rows, entity_to_idx)
    valid_pairs_np, y_valid = encode_rows(valid_rows, entity_to_idx)
    test_pairs_np, y_test = encode_rows(test_rows, entity_to_idx)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    metric_rows: list[dict[str, object]] = []
    prediction_rows: list[dict[str, object]] = []

    for model_name in selected_models:
        result = fit_predict_one_model(
            model_name=model_name,
            num_entities=len(entity_categories),
            train_pairs_np=train_pairs_np,
            y_train=y_train,
            valid_pairs_np=valid_pairs_np,
            y_valid=y_valid,
            test_pairs_np=test_pairs_np,
            args=args,
        )
        metrics = evaluate_predictions(y_test, result["y_pred"], result["positive_proba"])
        metric_row = {
            "model": model_name,
            "threshold": result["threshold"],
            "fit_time_s": result["fit_time_s"],
            "predict_time_s": result["predict_time_s"],
            "epochs_run": result["epochs_run"],
            "best_epoch": result["best_epoch"],
            "best_monitor_loss": result["best_monitor_loss"],
            **metrics,
        }
        metric_rows.append(metric_row)

        prediction_columns = [col for col in ["atom_id", "pair_id", "entity_1", "entity_2", "label", "split"] if col in test_rows[0]]
        for row, proba, pred in zip(test_rows, result["positive_proba"], result["y_pred"], strict=True):
            prediction_row = {col: row[col] for col in prediction_columns}
            prediction_row["model"] = model_name
            prediction_row["positive_proba"] = float(proba)
            prediction_row["prediction"] = int(pred)
            prediction_rows.append(prediction_row)

    metric_fieldnames = [
        "model",
        "threshold",
        "fit_time_s",
        "predict_time_s",
        "epochs_run",
        "best_epoch",
        "best_monitor_loss",
        "accuracy",
        "f1",
        "precision",
        "recall",
        "positive_rate_true",
        "positive_rate_pred",
        "average_precision",
        "roc_auc",
    ]
    prediction_fieldnames = [
        *[col for col in ["atom_id", "pair_id", "entity_1", "entity_2", "label", "split"] if col in test_rows[0]],
        "model",
        "positive_proba",
        "prediction",
    ]
    write_csv(args.output_dir / "metrics.csv", metric_rows, metric_fieldnames)
    write_csv(args.output_dir / "predictions.csv", prediction_rows, prediction_fieldnames)
    write_json(
        args.output_dir / "metadata.json",
        {
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "data_path": str(args.data_path.resolve()),
            "models": selected_models,
            "device": args.device,
            "seed": args.seed,
            "threshold_mode": args.threshold_mode,
            "decision_threshold": args.decision_threshold,
            "embedding_dim": args.embedding_dim,
            "relation_dim": args.relation_dim,
            "epochs": args.epochs,
            "lr": args.lr,
            "weight_decay": args.weight_decay,
            "batch_size": args.batch_size,
            "patience": args.patience,
            "distance": args.distance,
            "entities": len(entity_categories),
            "train_rows": len(train_rows),
            "validation_rows": len(valid_rows),
            "test_rows": len(test_rows),
        },
    )
    (args.output_dir / "findings.md").write_text(build_findings(metric_rows, args), encoding="utf-8")

    for row in metric_rows:
        print(
            "{model:>8}  acc={accuracy:.4f}  f1={f1:.4f}  ap={average_precision:.4f}  "
            "auc={roc_auc:.4f}  threshold={threshold:.4f}".format(**row)
        )


if __name__ == "__main__":
    main()
